set(_AMENT_PACKAGE_NAME "package_example")
set(package_example_VERSION "0.0.0")
set(package_example_MAINTAINER "akhil-rover <akhil-rover@todo.todo>")
set(package_example_BUILD_DEPENDS )
set(package_example_BUILDTOOL_DEPENDS "ament_cmake")
set(package_example_BUILD_EXPORT_DEPENDS )
set(package_example_BUILDTOOL_EXPORT_DEPENDS )
set(package_example_EXEC_DEPENDS )
set(package_example_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(package_example_GROUP_DEPENDS )
set(package_example_MEMBER_OF_GROUPS )
set(package_example_DEPRECATED "")
set(package_example_EXPORT_TAGS)
list(APPEND package_example_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
